### ISSUE TITLE
Creating a landing page web/mobile design for keysign website.

### ISSUE THREAD

**Issue by mrbusysky** [Keysign-Wallet/keysign-web#1]
**We are looking for someone or a team of people to make a landing page design.**

**Project requirements:**
* Flat modern design
* Non-rectangular header
* Lack of sharp edges
* Infographics
* Mobile design must be included with web page design
* Color scheme - surprise us.
* Dark theme also needs to be included for both web/mobile designs

**Design requirements can be found [here](https://docs.google.com/document/d/1GoWDIRLSUUmK1O1ezIpyBHU7Lm8AYpLwGYk4wOXaY2Q/edit?usp=sharing).**

**Rule:**
* You need to submit a [figma.com](https://www.figma.com) link for your designs
* You must have public rights or project rights for all images used.
* You can do this project with a team.
* Only one person/team can win this bounty.
* You must put your wallet address(‘s) under the links for your design in your reply.
* If you’re a team you must put which wallet gets how much sent to it.

Information:
* You can find information about the extension [here](https://github.com/mrbusysky/keysign)

**Information:** 
Mrsky and Abhay are paying this bounty.

[Message us here if you have any questions](https://thenewboston.slack.com/archives/C01FY5A946P)

Bounty: 30,000 TNBC

**Comment by SOHDA31** [comment]
Hi there! I gave it a try. Let me know if these designs are valid or not and if any changes are required. Hope you guys like them. [https://www.figma.com/file/6emugJeTvwt2L73TfJSpnS/Keysign-Landing-Page?node-id=0%3A1]

**Comment by SOHDA31** [comment]
Account number : 5257c00dc543a348f3aee0c7871d7e659d4ec63b68838302f3f4da978e13c92a

**Comment by mrbusysky** [comment]
We are closing this bounty since we didn't find any submissions we like. Those who put in the effort will be rewarded.

**Comment by stavio12** [comment]
If you get a design you like hit me up so i help with implementing of the website and i think i can get someone to also help with the mobile apps too...
Just hit me up if you need help there
